### ISSUE TITLE
Exception on update with pip: no file called cluster-1.3.3-py3.6.egg

### ISSUE THREAD

**Issue by 1kastner** [exhuma/python-cluster#26] opened 2017-08-13 13:55 UTC
There is a bug when I try to update the package via pip.

        (E:\path\to\miniconda) C:\Users\current_user>pip install --upgrade cluster
        Collecting cluster
          Downloading cluster-1.4.0-py2.py3-none-any.whl
        Installing collected packages: cluster
          Found existing installation: cluster 1.3.3
            Uninstalling cluster-1.3.3:
              Successfully uninstalled cluster-1.3.3
        Successfully installed cluster-1.4.0
        Traceback (most recent call last):
          File "E:\path\to\miniconda\Scripts\pip-script.py", line 5, in <module>
            sys.exit(pip.main())
          File "E:\path\to\miniconda\lib\site-packages\pip\__init__.py", line 249, in main
            return command.main(cmd_args)
          File "E:\path\to\miniconda\lib\site-packages\pip\basecommand.py", line 252, in main
            pip_version_check(session)
          File "E:\path\to\miniconda\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
            installed_version = get_installed_version("pip")
          File "E:\path\to\miniconda\lib\site-packages\pip\utils\__init__.py", line 838, in get_installed_version
            working_set = pkg_resources.WorkingSet()
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
            self.add_entry(entry)
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
            for dist in find_distributions(entry, True):
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1949, in find_eggs_in_zip
            if metadata.has_metadata('PKG-INFO'):
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1463, in has_metadata
            return self.egg_info and self._has(self._fn(self.egg_info, name))
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1823, in _has
            return zip_path in self.zipinfo or zip_path in self._index()
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1703, in zipinfo
            return self._zip_manifests.load(self.loader.archive)
          File "E:\path\to\miniconda\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1643, in load
            mtime = os.stat(path).st_mtime
        FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'E:\\path\\to\\miniconda\\lib\\site-packages\\cluster-1.3.3-py3.6.egg'
        
The last row means "The system could not find the file".

When I tried to import "cluster" after this, it seemed like everything was working again.

**Comment by exhuma** [comment] 2018-05-13 17:47
I can't reproduce this error. Does not seem to be related to the library itself, but rather an issue with miniconda (see output below). I will close this issue. If it turns out to be related to the library afterall, feel free to re-open it.

```
┌─[19:45:11] exhuma@blackdragon
└─~/tmp› pyvenv env
┌─[19:45:20] exhuma@blackdragon
└─~/tmp› ./env/bin/pip install --no-cache-dir cluster==1.3.3
Collecting cluster==1.3.3
  Downloading https://files.pythonhosted.org/packages/d7/1c/fe6d563d8e8f90f78f327c1f47c0523420c63b597be3f8db093c3bb7521d/cluster-1.3.3-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 68kB/s
Installing collected packages: cluster
Successfully installed cluster-1.3.3
┌─[19:45:31] exhuma@blackdragon
└─~/tmp› ./env/bin/pip install --no-cache-dir -U cluster
Collecting cluster
  Downloading https://files.pythonhosted.org/packages/2c/fb/7a8a4f6c56d04eaad8b29629c6c42685027c0f0cef5c665dcbd47bc9801f/cluster-1.4.0-py2.py3-none-any.whl
Installing collected packages: cluster
  Found existing installation: cluster 1.3.3
    Uninstalling cluster-1.3.3:
      Successfully uninstalled cluster-1.3.3
Successfully installed cluster-1.4.0
┌─[19:45:42] exhuma@blackdragon
└─~/tmp›
```

**Closed by exhuma** 2018-05-13 17:47 UTC

**Comment by 1kastner** [comment] 2018-05-16 10:55
Thanks for looking at it, now everything seems to be fine.
